version: "3.9"

name: myapi

services:
  api:
    build:
      context: ./backend/dailyDo-todo-app
      dockerfile: Dockerfile
    depends_on:    # it will run postgres_db first before api
        - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    networks:
      - my-api-net
  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
        - POSTGRES_USER=allauddin
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=mydatabase
    ports:
        - '5433:5432'  #right: default port of postgres
    volumes:   #postgres put its data on this location. those volume is linked with this location.
        - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net
# As image is immutable thus we can't store data in image of postgres. So to keep data persistent even if we stop and restart to store data we use volume
volumes:   #created volume here
  postgres_db:
    driver: local

networks:
  my-api-net:  # Define the custom network
